In [2]:
import numpy as np

## DataTypes & Attributes

In [3]:
# Numpy main datatype is ndarray

array_one = np.array([9, 7, 6])
array_one

array([9, 7, 6])

In [4]:
type(array_one)

numpy.ndarray

In [5]:
array_two = np.array([[1, 2, 3.0],
                     [3, 3, 4.0]])

array_three = np.array([[[1, 2, 3],
                         [3, 6, 7],
                         [6, 7, 9],
                         [6, 7, 9]],
                        [[10, 11, 12],
                         [9, 7, 6],
                         [16, 17, 18],
                         [7, 6, 7]]])

array_two

array([[1., 2., 3.],
       [3., 3., 4.]])

In [6]:
array_three

array([[[ 1,  2,  3],
        [ 3,  6,  7],
        [ 6,  7,  9],
        [ 6,  7,  9]],

       [[10, 11, 12],
        [ 9,  7,  6],
        [16, 17, 18],
        [ 7,  6,  7]]])

In [7]:
# 2 arrays 4 rows 3 columns

array_three.shape

(2, 4, 3)

In [8]:
# number of dimensions of an array
array_one.ndim, array_two.ndim, array_three.ndim

(1, 2, 3)

In [9]:
# datatype of an array
array_one.dtype, array_two.dtype, array_three.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [10]:
# total size of an array
array_one.size, array_two.size, array_three.size

(3, 6, 24)

In [11]:
type(array_one), type(array_two), type(array_three)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [12]:
# Create a DataFrame from a Numpy array

import pandas as pd

df = pd.DataFrame(array_two)
df

     0    1    2
0  1.0  2.0  3.0
1  3.0  3.0  4.0

In [13]:
# select block
df = pd.DataFrame(array_three[0])
df

   0  1  2
0  1  2  3
1  3  6  7
2  6  7  9
3  6  7  9

In [14]:
df = pd.DataFrame(array_three[1])
df

    0   1   2
0  10  11  12
1   9   7   6
2  16  17  18
3   7   6   7

In [15]:
# convert 3D array into 2D array
two_dim_array = array_three.reshape(8, 3)
df = pd.DataFrame(two_dim_array)
df

    0   1   2
0   1   2   3
1   3   6   7
2   6   7   9
3   6   7   9
4  10  11  12
5   9   7   6
6  16  17  18
7   7   6   7

In [16]:
# create a Numpy array

sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [18]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
zeros = np.zeros((3, 2))
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0, 20, size=(4, 5))
random_array

array([[ 1, 17, 17, 13, 17],
       [ 5,  6,  8,  4,  8],
       [19, 16, 19,  3, 15],
       [ 1,  7,  5,  0, 10]])

In [23]:
random_array.shape

(4, 5)

In [24]:
random_array.size

20

In [25]:
random_array_two = np.random.random((5, 3))
random_array_two.shape

(5, 3)

In [26]:
random_array_three = np.random.rand(5, 3)
random_array_three

array([[0.53201307, 0.62236571, 0.58763409],
       [0.08117291, 0.41637582, 0.04362541],
       [0.44088859, 0.38133251, 0.07348717],
       [0.35077626, 0.51387478, 0.7866756 ],
       [0.64023159, 0.12822539, 0.87628111]])

In [27]:
random_array_three.shape

(5, 3)

In [28]:
# Pseudo-random numbers
# Random seed: A seed is a starting value used by a pseudo-random number generator.
#Using the same seed allows us to reproduce the same sequence of random numbers, which is useful for reproducible ML experiments.
random_seed = np.random.seed(seed=0)
random_seed

random_array_four = np.random.randint(30, size=(5, 4))
random_array_four

array([[12, 15, 21,  0],
       [ 3, 27,  3,  7],
       [ 9, 19, 21, 18],
       [ 4, 23,  6, 24],
       [24, 12, 26,  1]])

In [29]:
# Viewing arrays and matrices
array_three[:2, :3, :3]

array([[[ 1,  2,  3],
        [ 3,  6,  7],
        [ 6,  7,  9]],

       [[10, 11, 12],
        [ 9,  7,  6],
        [16, 17, 18]]])

In [30]:
array_four = np.random.randint(20, size=(3, 4, 6, 8))
array_four

array([[[[ 6,  7, 14, 17,  5, 13,  8,  9],
         [19, 16, 19,  5, 15, 15,  0, 18],
         [ 3, 17, 19, 19, 19, 14,  7,  0],
         [ 1,  9,  0, 10,  3, 11, 18,  2],
         [ 0,  0,  4,  5,  6,  8, 17, 15],
         [ 4,  9, 10,  1,  1,  7,  9,  3]],

        [[ 6, 11, 14, 18,  0, 14,  3, 12],
         [10, 11,  4,  6,  4, 15,  3, 12],
         [ 4,  8, 14, 15,  3, 15, 13, 16],
         [17,  5,  9,  3,  0,  5,  0, 17],
         [18,  4,  2, 16,  3,  2, 10, 13],
         [16,  7,  9,  0, 10, 18, 11,  2]],

        [[ 2,  3,  3, 18, 14,  3, 17, 18],
         [14,  9,  1,  4, 10, 11,  8, 11],
         [ 2, 19, 16,  0,  0,  6, 19, 14],
         [10, 19,  8, 13,  2,  3,  2, 11],
         [13, 16,  8,  8, 19,  8,  2,  3],
         [12, 14,  0,  4,  3, 13, 11, 13]],

        [[13, 11, 16, 14, 16, 19,  1,  8],
         [ 0,  4,  6, 13,  7, 15,  9, 18],
         [ 8, 15, 11,  6, 15,  1, 12,  3],
         [18, 15,  3, 10, 12,  6,  3,  5],
         [11,  0, 11,  8, 10, 11,  5, 15],
         [ 8,  2, 19, 19, 14,  3,  3,  7]]],


       [[[ 9,  9,  9,  3, 14, 18, 12,  3],
         [ 9, 10, 13,  7,  7,  1, 12,  2],
         [ 2,  1,  5,  8,  4,  0, 11,  2],
         [ 5, 16,  8,  1, 17, 16,  3,  8],
         [ 4, 16,  3,  7,  3, 18, 17,  1],
         [18, 17,  2,  5,  5, 12, 12,  2]],

        [[15,  7,  7, 11, 17,  6,  7, 18],
         [11, 19, 17,  9, 14,  9, 18,  0],
         [ 9, 11, 17,  9,  0, 16, 10,  4],
         [ 3, 19,  8, 14,  0, 19,  8,  7],
         [13, 17,  0, 11,  4,  0, 10, 14],
         [18,  4,  3, 19,  7,  8, 13,  5]],

        [[ 0,  8, 15, 15, 11,  4,  7, 13],
         [10, 14, 17, 19,  3,  9, 18,  2],
         [19, 11, 18, 13,  1,  6, 10, 16],
         [16,  3, 17, 10,  9, 12, 13,  6],
         [ 6,  7,  8, 13,  7, 16, 15,  8],
         [ 3,  6, 17,  7,  2, 16, 18, 13]],

        [[ 4,  4, 12, 17,  1,  5,  1, 19],
         [19,  7,  9, 17,  9,  0, 19,  4],
         [17, 16,  3, 10,  1,  4,  4, 16],
         [16, 15, 10, 13,  8, 11,  6,  9],
         [15,  3, 19, 12, 18, 17, 10,  2],
         [ 1, 11,  3, 12,  4,  1, 17,  0]]],


       [[[ 7,  4,  3,  5,  6,  3,  2,  8],
         [ 1,  4,  0, 13, 19,  9,  5,  1],
         [ 7,  8,  7,  3, 12,  3,  6,  7],
         [19,  0,  5, 11,  9, 19,  7,  5],
         [ 8, 11, 14,  0,  8, 19,  6, 10],
         [19,  2,  0, 19, 14,  0, 19,  6]],

        [[ 1, 12, 18, 13,  9,  4, 17,  3],
         [ 2, 13, 15,  4,  9,  4, 17, 18],
         [13, 13,  2,  3,  9, 12, 15,  2],
         [19,  6, 14, 16, 15,  8,  0, 10],
         [11, 13,  7,  6, 13, 15,  9,  6],
         [11, 18,  7,  1,  9,  2, 18, 14]],

        [[ 5,  4, 18, 14, 18,  1, 12,  0],
         [ 9, 16,  2,  8, 19, 10, 16,  1],
         [ 0,  5,  2, 15,  3, 14,  5, 11],
         [19,  6,  6, 19,  6,  2,  6,  5],
         [ 5, 13,  9,  4, 13, 17,  3, 13],
         [19,  8, 13,  5, 16, 14,  5,  1]],

        [[ 5,  6, 12, 10, 14,  8,  7, 13],
         [ 5, 15, 10,  3, 10, 18,  3, 14],
         [18,  5,  4, 17,  5,  3,  5,  8],
         [ 4, 17,  1, 18,  1, 14, 17,  7],
         [11, 14, 16,  1, 17, 12, 14,  0],
         [ 2, 19, 14, 18, 11,  9, 14,  0]]]])

In [31]:
array_four[1:2].shape

(1, 4, 6, 8)

## Manipulating & comparing arrays

##Arithmetic

In [32]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
array_one + ones

array([[10.,  8.,  7.],
       [10.,  8.,  7.]])

In [34]:
array_one - ones

array([[8., 6., 5.],
       [8., 6., 5.]])

In [35]:
array_one * ones

array([[9., 7., 6.],
       [9., 7., 6.]])

In [36]:
array_one / ones

array([[9., 7., 6.],
       [9., 7., 6.]])

In [37]:
array_one * array_two

array([[ 9., 14., 18.],
       [27., 21., 24.]])

In [38]:
np.square(array_one)

array([81, 49, 36])

In [39]:
np.exp(array_one)

array([8103.08392758, 1096.63315843,  403.42879349])

## Aggregation

## Taking many values in an array and summarizing them into fewer values

Common NumPy aggregation functions
```
np.sum(a)	Sum of values
np.mean(a)	Average
np.min(a)	Smallest value
np.max(a)	Largest value
np.std(a)	Standard deviation
np.var(a)	Variance
np.median(a)	Middle value
np.argmin(a)	Index of smallest value
np.argmax(a)	Index of largest value
```

In [40]:
np.sum(array_one)

np.int64(22)

In [41]:
np.min(array_one)

np.int64(6)

In [42]:
np.max(array_one)

np.int64(9)

In [43]:
np.mean(array_one)

np.float64(7.333333333333333)

In [44]:
np.std(array_one)

np.float64(1.247219128924647)

## Reshaping & transposing

In [46]:
array_one

array([9, 7, 6])

In [47]:
array_two.shape

(2, 3)

In [48]:
array_three

array([[[ 1,  2,  3],
        [ 3,  6,  7],
        [ 6,  7,  9],
        [ 6,  7,  9]],

       [[10, 11, 12],
        [ 9,  7,  6],
        [16, 17, 18],
        [ 7,  6,  7]]])

In [50]:
array_three.shape

(2, 4, 3)

In [51]:
array_two * array_three

ValueError: operands could not be broadcast together with shapes (2,3) (2,4,3)

In [57]:
array_two_reshape = array_two.reshape(2, 3, 1)

array_two_reshape

array([[[1.],
        [2.],
        [3.]],

       [[3.],
        [3.],
        [4.]]])

In [59]:
array_two_reshape = np.random.randint(20, size=(2, 4, 3))

array_two_reshape

array([[[18, 16,  2],
        [ 6,  9,  2],
        [12,  9,  4],
        [ 4,  9, 10]],

       [[12,  8,  1],
        [ 5,  7,  0],
        [ 1,  3, 18],
        [18,  8, 18]]])

In [60]:
array_two_reshape * array_three

array([[[ 18,  32,   6],
        [ 18,  54,  14],
        [ 72,  63,  36],
        [ 24,  63,  90]],

       [[120,  88,  12],
        [ 45,  49,   0],
        [ 16,  51, 324],
        [126,  48, 126]]])

In [61]:
# Transpose = Transpose means changing the arrangement of an array by swapping it axes

array_two_reshape

array([[[18, 16,  2],
        [ 6,  9,  2],
        [12,  9,  4],
        [ 4,  9, 10]],

       [[12,  8,  1],
        [ 5,  7,  0],
        [ 1,  3, 18],
        [18,  8, 18]]])

In [62]:
array_two_reshape.T

array([[[18, 12],
        [ 6,  5],
        [12,  1],
        [ 4, 18]],

       [[16,  8],
        [ 9,  7],
        [ 9,  3],
        [ 9,  8]],

       [[ 2,  1],
        [ 2,  0],
        [ 4, 18],
        [10, 18]]])

In [63]:
array_two_reshape.T.shape

(3, 4, 2)

##

## ## Dot Product - multiply corresponding elements of two vectors, then add the results together

ex: a.b

In [66]:
np.random.seed(0)

mat1 = np.random.randint(30, size=(5, 3))
mat2 = np.random.randint(30, size=(5, 3))

mat1

array([[12, 15, 21],
       [ 0,  3, 27],
       [ 3,  7,  9],
       [19, 21, 18],
       [ 4, 23,  6]])

In [67]:
mat2

array([[24, 24, 12],
       [26,  1,  6],
       [ 7, 23, 14],
       [24, 17,  5],
       [25, 13,  8]])

In [68]:
dot_product = np.dot(mat1, mat2)
dot_product

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [69]:
# Transpose
mat1.T.shape

(3, 5)

In [70]:
mat1.T.shape, mat2.shape

((3, 5), (5, 3))

In [71]:
dot_product = np.dot(mat1.T, mat2)
dot_product

array([[ 865,  732,  313],
       [1566, 1180,  585],
       [1851, 1122,  678]])